apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJVMkZ5YTJsemVXRnVTVUU2WjJod1gzcG1iMnRZVm05TlNqbDZTSEJ2VDJGT1QwVnhjVFpTYmtkTVFtMW5NekpDYTJOeFN3PT0iCgkJfQoJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAoJImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiCn0=
type: kubernetes.io/dockerconfigjson
