server.port=8000

monolith.url=${MONOLITH_URL:http://localhost:8080}
movies.service.url=${MOVIES_SERVICE_URL:http://localhost:8081}
events.service.url=${EVENTS_SERVICE_URL:http://localhost:8082}

gradual.migration=${GRADUAL_MIGRATION:false}
movies.migration.percent=${MOVIES_MIGRATION_PERCENT:0}

logging.level.com.cinemaabyss.proxy=INFO
logging.level.org.springframework.web=INFO